services:
  pgdb:
    image: postgres:16
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appsecret
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro   
    healthcheck:                                   
      test: ["CMD-SHELL", "pg_isready -U appuser -d notesdb"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 8080
      DB_HOST: pgdb
      DB_PORT: 5432
      DB_USER: appuser
      DB_PASSWORD: appsecret
      DB_NAME: notesdb
      CORS_ORIGIN: http://localhost:3000
      JWT_SECRET: replace_me
    depends_on:
      pgdb:
        condition: service_healthy
    ports: ["8080:8080"]
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: notes-client
    restart: unless-stopped
    depends_on:
      - server
    environment:
      HOST: "0.0.0.0"
      PORT: "3000"
      REACT_APP_API_BASE_URL: "http://localhost:8080"
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  pgdata: